site_name: "ENEM"

repo_name: "2021.2-ENEM"
repo_url: "https://github.com/Requisitos-de-Software/2021.2-ENEM"

theme:
  name: "material"
  language: "pt"
  logo: "assets/favicon.svg"
  favicon: "assets/favicon.svg"
  palette:
    primary: "#fff"
    accent: "#0B4D9B"
  font:
    text: "Montserrat"
    code: "sans-serif"

extra_css:
  - stylesheets/styles.css

nav:
  - Início: index.md

  - Planejamento:
      - Metodologia: planejamento/metodologia.md
      - Ferramentas: planejamento/ferramentas.md
      - Cronograma: planejamento/cronograma.md

  - Pré-rastreabilidade:
      - Rich Picture: pre-rastreabilidade/rich_picture.md

  - Elicitação:
      - Técnicas de Elicitação:
          - Brainstorming: elicitacao/tecnicas-elicitacao/brainstorming.md
          - Entrevista: elicitacao/tecnicas-elicitacao/entrevista.md
          - Instrospecção: elicitacao/tecnicas-elicitacao/instrospeccao.md
          - Observação: elicitacao/tecnicas-elicitacao/observacao.md
          - Questionário: elicitacao/tecnicas-elicitacao/questionario.md
          - Storytelling: elicitacao/tecnicas-elicitacao/storytelling.md
      - Técnicas de Priorização:
          - MoSCoW: elicitacao/tecnicas-priorizacao/MoSCoW.md
          - Gráfico Tempo X Esforço: elicitacao/tecnicas-priorizacao/grafico-tempo-esforço.md
      - Resultado: elicitacao/resultado.md

  - Modelagem:
    - Casos de Uso: modelagem/casos-de-uso.md
    - Cenários: modelagem/cenarios.md
    - Especificação Suplementar: modelagem/especificacao-suplementar.md
    - Léxicos: modelagem/lexicos.md
    - Ágil: 
      - Backlog: modelagem/agil/backlog.md
      - Historias de Usuário: 
        - US01 : modelagem/agil/historias-usuario/US1.md
        - US02 : modelagem/agil/historias-usuario/US2.md
        - US03 : modelagem/agil/historias-usuario/US3.md
        - US04 : modelagem/agil/historias-usuario/US4.md
        - US05 : modelagem/agil/historias-usuario/US5.md
        - US06 : modelagem/agil/historias-usuario/US6.md
        - US07 : modelagem/agil/historias-usuario/US7.md
        - US08 : modelagem/agil/historias-usuario/US8.md
        - US09 : modelagem/agil/historias-usuario/US9.md
        - US10 : modelagem/agil/historias-usuario/US10.md
        - US11 : modelagem/agil/historias-usuario/US11.md
        - US12 : modelagem/agil/historias-usuario/US12.md
        - US13 : modelagem/agil/historias-usuario/US13.md
        - US14 : modelagem/agil/historias-usuario/US14.md
    - NRF Framework: modelagem/nfrframework.md

  - Sprints:
      - Sprint 1: sprints/sprint1.md
      - Sprint 2: sprints/sprint2.md

  - Apresentações:
      - Apresentação 1: apresentacoes/apresentacao1.md
      - Apresentação 2: apresentacoes/apresentacao2.md
      - Apresentação 3: apresentacoes/apresentacao3.md
      - Apresentação 4: apresentacoes/apresentacao4.md

plugins:
  - search
  
dev_addr: "0.0.0.0:8000"
