site_name: "ENEM"

repo_name: "2021.2-ENEM"
repo_url: "https://github.com/Requisitos-de-Software/2021.2-ENEM"

theme:
  name: "material"
  language: "pt"
  logo: "assets/favicon.svg"
  favicon: "assets/favicon.svg"
  palette:
    primary: "#fff"
    accent: "#0B4D9B"
  font:
    text: "Montserrat"
    code: "sans-serif"

extra_css:
  - stylesheets/styles.css

nav:
  - Início: index.md
  - Planejamento:
      # Metodologia: planejamento/metodologia.md
      - Metodologia: planejamento/metodologia.md

      # - Ferramentas: planejamento/ferramentas.md
      - Ferramentas: planejamento/ferramentas.md

      # - Cronograma: planejamento/metodologia.md
      - Cronograma: planejamento/cronograma.md

  - Pré-rastreabilidade:
      # Rich picture: planejamento/rich_picture.md
      - Rich Picture: pre-rastreabilidade/rich_picture.md

  - Elicitação:
      - Técnicas de Elicitação:
          # - Análise de Documento: elicitacao/analise-de-documento.md
          - Análise de Documento: elicitacao/tecnicas-elicitacao/analise-de-documento.md

          # - Brainstorming: elicitacao/brainstorming.md
          - Brainstorming: elicitacao/tecnicas-elicitacao/brainstorming.md

          # - Entrevista: elicitacao/entrevista.md
          - Entrevista: elicitacao/tecnicas-elicitacao/entrevista.md

          # - Instrospecção: elicitacao/instrospeccao.md
          - Instrospecção: elicitacao/tecnicas-elicitacao/instrospeccao.md

          # - Observação: elicitacao/observacao.md
          - Observação: elicitacao/tecnicas-elicitacao/observacao.md

          # - Questionário: elicitacao/questionario.md
          - Questionário: elicitacao/tecnicas-elicitacao/questionario.md

          # - Storytelling: elicitacao/storytelling.md
          - Storytelling: elicitacao/tecnicas-elicitacao/storytelling.md

      - Técnicas de Priorização:
          # - MoSCoW: elicitacao/tecnicas-priorizacao/MoSCoW.md
          - MoSCoW: elicitacao/tecnicas-priorizacao/MoSCoW.md

          # - Gráfico Tempo X Esforço: elicitacao/tecnicas-priorizacao/grafico-tempo-esforço.md
          - Gráfico Tempo X Esforço: elicitacao/tecnicas-priorizacao/grafico-tempo-esforço.md

      - Resultado: elicitacao/resultado.md

  - Apresentações:
      - Apresentação 1: apresentacoes/apresentacao1.md
      - Apresentação 2: apresentacoes/apresentacao2.md

plugins:
  - search
dev_addr: "0.0.0.0:8000"
